CREATE TABLE mata_pelajaran (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL
);
INSERT INTO mata_pelajaran (title) VALUES
('Pendidikan Agama Islam'),
('Pendidikan Agama Kristen'),
('Pendidikan Agama Katolik'),
('Pendidikan Agama Hindu'),
('Pendidikan Agama Buddha'),
('Pendidikan Pancasila dan Kewarganegaraan'),
('Bahasa Indonesia'),
('Matematika'),
('Ilmu Pengetahuan Alam'),
('Ilmu Pengetahuan Sosial'),
('Bahasa Inggris'),
('Seni Budaya'),
('Pendidikan Jasmani, Olahraga, dan Kesehatan'),
('Prakarya'),
('Informatika'),
('Bahasa Daerah'),
('Fisika'),
('Kimia'),
('Biologi'),
('Ekonomi'),
('Geografi'),
('Sejarah'),
('Sosiologi'),
('Akuntansi'),
('Bahasa Jepang'),
('Bahasa Mandarin'),
('Bahasa Arab');
